// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zviumkdiepriiqttchka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2aXVta2RpZXByaWlxdHRjaGthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNzMxMjEsImV4cCI6MjA2OTk0OTEyMX0.MMm9s22QQX_gUiAgPGOGtbMgGuIvs7dq2bY8cdTJnFs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});